-- MySQL Script generated by MySQL Workbench
-- Mon Nov  4 20:59:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mlb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mlb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mlb` DEFAULT CHARACTER SET utf8 ;
USE `mlb` ;

-- -----------------------------------------------------
-- Table `mlb`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mlb`.`players` (
  `playerid` INT NOT NULL,
  `playerName` VARCHAR(45) NOT NULL,
  `dateOfBirth` DATE NOT NULL,
  `height` INT NULL,
  `weight` INT NULL,
  PRIMARY KEY (`playerid`))
ENGINE = InnoDB
COMMENT = 'p';


-- -----------------------------------------------------
-- Table `mlb`.`leagues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mlb`.`leagues` (
  `leagueName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`leagueName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mlb`.`division`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mlb`.`division` (
  `divisionName` VARCHAR(100) NOT NULL,
  `leagueName` VARCHAR(100) NULL,
  PRIMARY KEY (`divisionName`),
  INDEX `divison_league_fk_idx` (`leagueName` ASC) VISIBLE,
  CONSTRAINT `divison_league_fk`
    FOREIGN KEY (`leagueName`)
    REFERENCES `mlb`.`leagues` (`leagueName`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mlb`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mlb`.`team` (
  `teamAcronym` VARCHAR(3) NOT NULL,
  `teamName` VARCHAR(100) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `divisionName` VARCHAR(45) NOT NULL,
  `worldseriesWins` INT NOT NULL,
  `leagueWins` INT NOT NULL,
  `divisonWins` INT NOT NULL,
  PRIMARY KEY (`teamAcronym`),
  INDEX `team_divison_fk_idx` (`divisionName` ASC) VISIBLE,
  CONSTRAINT `team_divison_fk`
    FOREIGN KEY (`divisionName`)
    REFERENCES `mlb`.`division` (`divisionName`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mlb`.`awards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mlb`.`awards` (
  `awardName` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`awardName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mlb`.`stadium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mlb`.`stadium` (
  `stadiumName` VARCHAR(100) NOT NULL,
  `roofType` VARCHAR(100) NOT NULL,
  `capacity` INT NULL,
  `openingYear` YEAR NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `teamAcronym` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`stadiumName`),
  INDEX `stadium_team_fk_idx` (`teamAcronym` ASC) VISIBLE,
  CONSTRAINT `stadium_team_fk`
    FOREIGN KEY (`teamAcronym`)
    REFERENCES `mlb`.`team` (`teamAcronym`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mlb`.`roster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mlb`.`roster` (
  `rosterid` INT NOT NULL,
  `teamAcronym` VARCHAR(3) NOT NULL,
  `playerid` INT NOT NULL,
  `season` YEAR NOT NULL,
  `pitcher_batter` ENUM('Pitcher', 'Batter') NOT NULL,
  PRIMARY KEY (`rosterid`),
  INDEX `player_roster_fk_idx` (`playerid` ASC) VISIBLE,
  INDEX `team_roster_fk_idx` (`teamAcronym` ASC) VISIBLE,
  UNIQUE INDEX `player_year_team_uq` (`pitcher_batter` ASC, `playerid` ASC, `teamAcronym` ASC, `season` ASC) VISIBLE,
  CONSTRAINT `player_roster_fk`
    FOREIGN KEY (`playerid`)
    REFERENCES `mlb`.`players` (`playerid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `team_roster_fk`
    FOREIGN KEY (`teamAcronym`)
    REFERENCES `mlb`.`team` (`teamAcronym`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mlb`.`batters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mlb`.`batters` (
  `rosterid` INT NOT NULL,
  `gamesPlayed` INT NOT NULL,
  `atBats` INT NOT NULL,
  `runs` INT NOT NULL,
  `hits` INT NOT NULL,
  `doubles` INT NULL,
  `triples` INT NULL,
  `homeRuns` INT NULL,
  `runsBattedIn` INT NULL,
  `stolenBases` INT NULL,
  `walks` INT NULL,
  `strikeouts` INT NULL,
  `onBasePercentage` DECIMAL(4,3) NULL,
  `slugging` DECIMAL(4,3) NULL,
  PRIMARY KEY (`rosterid`),
  CONSTRAINT `batters_roster_fk`
    FOREIGN KEY (`rosterid`)
    REFERENCES `mlb`.`roster` (`rosterid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mlb`.`pitchers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mlb`.`pitchers` (
  `rosterid` INT NOT NULL,
  `gamesPitched` INT NOT NULL,
  `era` DECIMAL(4,2) NULL,
  `completeGames` INT NOT NULL,
  `shutouts` INT NULL,
  `inningsPitched` DECIMAL(4,1) NOT NULL,
  `hitsAllowed` INT NULL,
  `runsAllowed` INT NULL,
  `earnedRunsAllowed` INT NULL,
  `homerunsAllowed` INT NULL,
  `walks` INT NULL,
  `strikeouts` INT NULL,
  `whip` DECIMAL(4,3) NULL,
  PRIMARY KEY (`rosterid`),
  CONSTRAINT `pitcherss_roster_fk`
    FOREIGN KEY (`rosterid`)
    REFERENCES `mlb`.`roster` (`rosterid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mlb`.`awardWinners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mlb`.`awardWinners` (
  `awardName` VARCHAR(100) NOT NULL,
  `playerid` INT NOT NULL,
  `yearWon` YEAR NOT NULL,
  PRIMARY KEY (`awardName`, `playerid`, `yearWon`),
  INDEX `players_awards_fk_idx` (`playerid` ASC) INVISIBLE,
  UNIQUE INDEX `unique_player_year_award` (`awardName` ASC, `yearWon` ASC, `playerid` ASC) VISIBLE,
  CONSTRAINT `winners_awards_fk`
    FOREIGN KEY (`awardName`)
    REFERENCES `mlb`.`awards` (`awardName`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `players_awards_fk`
    FOREIGN KEY (`playerid`)
    REFERENCES `mlb`.`players` (`playerid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
